require("dotenv").config();
module.exports={
    PORT:process.env.PORT,
    DATABASE_URL:process.env.DATABASE_URL,
    JWT_SECRET:process.env.JWT_SECRET,
    NODE_ENV:process.env.NODE_ENV,
    TWILIO_ACCOUNT_SID:process.env.TWILIO_ACCOUNT_SID,
    TWILIO_AUTH_TOKEN:process.env.TWILIO_AUTH_TOKEN,
    TWILIO_PHONE_NUMBER:process.env.TWILIO_PHONE_NUMBER,
    key_id:process.env.key_id,
    key_secret:process.env.key_secret
}